# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron:  '0 */3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X GET ${{secrets.HEROKU_URL}}
